spring:
  quartz:
    job-store-type: jdbc
    properties:
      # 调度实例配置
      org.quartz.scheduler.instanceName: MyTestClusteredScheduler
      org.quartz.scheduler.instanceId: AUTO
      # 线程池配置
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 25
      org.quartz.threadPool.threadPriority: 5
      # 任务存储配置
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartz
      org.quartz.jobStore.isClustered: true
      # 数据源配置
      org.quartz.dataSource.quartz.driver: com.mysql.jdbc.Driver
      org.quartz.dataSource.quartz.URL: ${spring.datasource.url}
      org.quartz.dataSource.quartz.user: ${spring.datasource.username}
      org.quartz.dataSource.quartz.password: ${spring.datasource.password}
      org.quartz.dataSource.quartz.provider: hikaricp

  datasource:
    url: jdbc:mysql://localhost:3306/quartz-test
    username: root
    password: 123456

testJob:
  cron: "0/5 * * * * ?"

