spring:
  application:
    #应用名称
    name: ms-registry2
server:
  #注册中心端口
  port: 8082
eureka:
  instance:
    #注册中心域名
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://ms-registry1:8080/eureka


