spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          #          uri: http://localhost:8081
          uri: lb://users-service
          predicates:
            - Path=/users/**
            - Cookie=test, 123
            - Cookie=test2, 456
            - Header=X-request-id, users-service
            - Method=GET
            - Query=a,123
            - Between=2018-01-01T00:00:00.000+08:00, 2018-12-31T23:59:59.999+08:00
          filters:
            - AddResponseHeader=X-test,1
            - RemoveRequestHeader=Set-Cookie
            - AddRequestParameter=foo,123
            - PrefixPath=/myservice
            - name: Hystrix
                args:
                  name: usersFallbackCommand
                  fallbackUri: forward:/users/fallback
            - name: RequestRateLimiter
                args:
                  # 允许用户每秒最大请求数，多余的请求将会等待
                  redis-rate-limiter.replenishRate: 10
                  # 一秒内允许用户最大请求数，多余的请求将会丢弃
                  redis-rate-limiter.burstCapacity: 20
                  # 流量的限制解析器
                  key-resolver: "#{@pathKeyResolver}"

  redis:
    host: localhost
    port: 6379
    database: 1
