server:
  port: 0
spring:
  application:
    name: ms-config-client
  cloud:
    config:
      discovery:
        enabled: true
        #配置中心应用名
        service-id: ms-config-server
#      profile: test
      username: demo
      password: 123456
  profiles:
    active: test
eureka:
  client:
    service-url:
      defaultZone: http://http://ms-registry1:8080/eureka/